[package]
name = "py_rust_faces"
version = "0.2.0"
edition = "2021"

[lib]
name = "py_rust_faces"
crate-type = ["cdylib"]

[dependencies]
image = "0.24.6"
numpy = "0.19.0"
pyo3 = "0.19.0"
rust-faces = {path = ".." }
